//
//  StoryViewModel.swift
//  QuizXguide
//
//  Created by Aleksandr Ataev on 26.02.2024.
//

import Foundation

final class StoryViewModel: ObservableObject {

    @Published var showStory: Bool = false
    @Published var currentStory: String = ""

    @Published var allStories: [StoryBundle] = [
        StoryBundle(circleImage: "One", stories: [Story(imageURL: "StoryOne",
                                                        title: "USD/JPY: Dollar Steady Well Above ¥150.00 as Japan Stays Muted on Possible Intervention",
                                                        shortDescription: "Exchange rate has been floating above the psychological level for a few days, adding pressure on Japan to step in and bring it down.",
                                                        fullDescription: "Exchange rate has been floating above the psychological level for a few days, adding pressure on Japan to step in and bring it down. \n\nThe  USDJPY pair is comfortably resting above the key ¥150.00 level, currently trading near ¥150.40. The US dollar has pinned its valuation against the weaker yen as if it’s subtly taunting Japan’s officials to consider a move. Previously, whenever the USDJPY peaked above ¥150.00, there would be a warning from Japan. \n\nA languishing yen is generally good for exports but bad for imports as it makes foreign goods worth more. With that said, Japan’s officials have been tight-lipped on a possible intervention intended to raise the yen’s valuation. In September 2022, Japan sold roughly $20 billion to buy yen, and then another $40 billion in October. The effect was short-lived. \n\nStateside, the higher-for-longer interest rate narrative has supported the bullish case for the US dollar. Traders have largely priced in an interest-rate skip at the Federal Reserve’s March meeting. Further, more analysts, including those at Goldman Sachs, are calling for another rate skip at the late-April meeting.")]),

        StoryBundle(circleImage: "Two", stories: [Story(imageURL: "StoryTwo",
                                                        title: "EUR/USD: Euro Picks Up Pace to Float Above $1.08 on Track for 8th Day of Winnings",
                                                        shortDescription: "Exchange rate is struggling to overcome the 200-day moving average positioned right at current market prices.",
                                                        fullDescription: "Exchange rate is struggling to overcome the 200-day moving average positioned right at current market prices. \n\nThe EURUSD pair was off to a quiet start of Friday trading. The exchange rate ticked higher to $1.0830 and was looking to close its eighth straight day of gains, buoyed higher by an increased bullish sentiment toward the euro. A day of no big data is on deck, promising to usher in more technical and less fundamental moves. \n\nSpeaking of technical analysis, a major resistance is looming over the EURUSD. Current market prices are hitting the 200-day moving average – a long-term indicator used to define whether the trend is bullish or bearish. In layman’s terms – price under the line means bearish and price over the line means bullish. \n\nWith that said, the US dollar could not sustain its short-term spike fueled by the latest Fed meeting minutes. According to the release, rates are likely to stay at their 23-year high of 5.50% to 5.25% at least until the Federal Reserve’s late-April meeting, leapfrogging the upcoming one in March.")]),

        StoryBundle(circleImage: "Three", stories: [Story(imageURL: "StoryThree",
                                                          title: "GBP/USD: Sterling Pares Gains to $1.2600 as FX Deals Go Quiet in Wait of Key US Report",
                                                          shortDescription: "Fed meeting minutes are scheduled to drop today and markets are tuning in to hear the latest from policymakers.",
                                                          fullDescription: "Fed meeting minutes are scheduled to drop today and markets are tuning in to hear the latest from policymakers. \n\nThe GBPUSD pair was off to a muted start on Wednesday as market participants shifted their focus to an upcoming Federal Reserve report. The pair struggled to keep up with a quick pump yesterday and erased the majority of its daily gains before market close. \n\nThe sterling shot up to $1.2660 but later lost momentum and ticked down to levels near the $1.2600 handle. Early in today’s session, the pair gravitated toward the $1.2630 mark as the broad FX deal space was tuning in for the latest update from the US central bank. \n\nThe Fed will release its minutes from the last meeting three weeks ago. Back then, America’s central banking elite left rates untouched and vowed to start cutting at a later point, leapfrogging the March window. With that in mind, volatility may pick up today if traders uncover any hints of an early rate trim.")]),

        StoryBundle(circleImage: "Four", stories: [Story(imageURL: "StoryFour",
                                                         title: "USD/JPY: Dollar Steady Above ¥150 with Rate Sandwiched Between Clashing Policy Views",
                                                         shortDescription: "Stubborn US inflation builds out the higher-for-longer interest rate narrative, while Japan falls into recession, bruising its own currency.",
                                                         fullDescription: "Stubborn US inflation builds out the higher-for-longer interest rate narrative, while Japan falls into recession, bruising its own currency. \n\nThe USDJPY pair is comfortably trading above the psychological ¥150.00 level as the two sides clash over divergent policy views. The exchange rate, floating near a three-month high of ¥150.50, got sandwiched between stubborn inflation from the US and looming recession from Japan. \n\nStateside, inflation for January remained elevated at 3.1% from a year ago. The figure fueled speculation that the Federal Reserve won’t rush to reduce the benchmark interest rate. A higher-for-longer rate narrative is generally good for the US dollar, yielding better riskless returns. \n\nIn Japan, officials are scrambling to contain the yen’s fall. This recent low prompted warnings from the Japanese government that it might step in and shore up the yen by scooping up boatloads of it. Still, with recession knocking at the door, Japan is caught in a limbo whether to abandon its easy-money policies or have them stay in a bid to buoy the economy.")]),

        StoryBundle(circleImage: "Five", stories: [Story(imageURL: "StoryFive",
                                                         title: "EUR/USD: Euro Extends Upside to Hit 100-Day MA at $1.0790 After Three Winning Sessions",
                                                         shortDescription: "Fed’s meeting minutes on deck for Wednesday are key to gauging central bankers’ mood over the rate-cutting campaign.",
                                                         fullDescription: "Fed’s meeting minutes on deck for Wednesday are key to gauging central bankers’ mood over the rate-cutting campaign.\n\nThe EURUSD kicked off weekly trading on an upbeat note, extending a three-day rise. Eurozone’s currency advanced a tiny 0.1% to hover under $1.08, a level which coincides with the trajectory of the 100-day moving average. A break above it would indicate that bullish efforts may carry the pair higher. \n\nFX markets are watching for the latest from the Federal Reserve. Slated for Wednesday, the US central bank’s meeting minutes will be released, shedding light on what policymakers discussed at their gathering three weeks ago. Back then, markets had a sharp selloff reaction over Fed chair Jay Powell’s remarks. \n\nIn other corners of the currency space, a calm opening of the session is unfolding as US traders are breaking for Washington’s Birthday. While stocks won’t open for deals, FX will stay active, likely offering lighter volumes and thinner liquidity. It can only mean one thing – time to get technical.")]),

        StoryBundle(circleImage: "Six", stories: [Story(imageURL: "StorySix",
                                                        title: "USD/JPY: Yen Recoups Recent Losses After Data Points to Recession in Japan’s Economy",
                                                        shortDescription: "Surprise dip into recession for the fourth-quarter complicated the path forward for the Bank of Japan and its expected policy tweak.",
                                                        fullDescription: "Surprise dip into recession for the fourth-quarter complicated the path forward for the Bank of Japan and its expected policy tweak. \n\nThe USDJPY pair drifted lower to start Thursday trading after data showed Japan’s economy slipped into an unexpected recession. The exchange rate tumbled to levels near ¥150.00 after previously floating at a three-month high above ¥150.80 on increased US dollar strength. \n\nRecouping some of the recent losses came with a sting for the Japanese economy which shrank 0.4% in the December quarter from a year ago. The print was below the estimate for a 1.4% growth and followed a 3.3% year-on-year contraction for the previous three-month time span. \n\nOn a quarterly basis, the numbers weren’t too good either. A 0.1% fourth-quarter contraction following a shrinking of 0.8% in the third quarter. Two consecutive quarters of falling growth technically meets the definition of recession. And that complicates the expected abandonment of the Bank of Japan’s easy-money policies as it considers a rate hike for the first time since 2007.")]),

        StoryBundle(circleImage: "Seven", stories: [Story(imageURL: "StorySeven",
                                                          title: "GBP/USD: Sterling Drops to $1.2540 After UK Inflation Undershoots to 4.0% in January",
                                                          shortDescription: "British currency slipped sharply on the news that consumer prices for January arrived lower than the 4.2% expected.",
                                                          fullDescription: "British currency slipped sharply on the news that consumer prices for January arrived lower than the 4.2% expected. \n\nThe GBPUSD pair dropped 0.4% early on Wednesday, led by a fresh weakening in the sterling. The British currency sold off after traders parsed the latest inflation data, showing price growth in the UK remained flat from the previous month. It was welcome news both for markets and the Bank of England. \n\nInflation in the UK was unchanged month on month, coming in at 4.0% on an annualized basis, undershooting analysts’ expectations for a print of 4.2%. Even better, headline inflation fell into negative territory to -0.6% from December. With that, the GBPUSD pair slipped for a second straight day, trading near $1.2540, down from a weekly high of $1.2690. \n\nThe downshift in consumer prices is a sigh of relief for markets as it is likely to solidify the Bank of England’s path to interest rate cuts. Previously, UK policymakers had telegraphed their intention to trim down borrowing costs as a “reward” for the consistent softening in price pressures.")]),

        StoryBundle(circleImage: "Eight", stories: [Story(imageURL: "StoryEight",
                                                          title: "EUR/USD: Euro Slips Away from $1.08 as US Inflation Comes In at 3.1% for January",
                                                          shortDescription: "Consumer prices kept heading lower in the past month, but failed to meet analysts’ consensus view of 2.9%.",
                                                          fullDescription: "Consumer prices kept heading lower in the past month, but failed to meet analysts’ consensus view of 2.9%. \n\nThe EURUSD pair fell early on Tuesday, slipping away from $1.08 as forex traders reacted to the latest inflation report out of the US. After several days of sideways trading, the exchange rate tumbled about 0.7% to $1.0720 following January’s consumer-price data which indicated the US economy didn’t cool as expected. \n\nInflation for January came in at 3.1%, above the anticipated 2.9% rate but below December’s 3.4%. Despite the markets sending good vibes, thoughts, and prayers all in an effort to receive more evidence that inflation is consistently moving lower and on track to hit the goldilocks area of 2%, home prices and rent prices pushed the headline figure up. \n\nThe Federal Reserve received yet another curveball as policymakers need to decide when to start unwinding interest rates. The CPI number is a mainstay indicator tracked by the central bank as it is closely tied to the level of interest rates. A higher print would suggest rates should stay higher for longer. A lower reading, in contrast, would convince Fed officials to keep on with the anticipated rate-cut campaign.")]),

        StoryBundle(circleImage: "Nine", stories: [Story(imageURL: "StoryNine",
                                                         title: "EUR/USD: Euro Edges Closer to $1.08 in Quiet Trading with No Big News to Stir Deals Up",
                                                         shortDescription: "European currency struggles to snap a three-week losing streak as it’s on track to slide out of this one in the red.",
                                                         fullDescription: "European currency struggles to snap a three-week losing streak as it’s on track to slide out of this one in the red. \n\nThe EURUSD pair was calmly humming along early on Friday as forex traders had muted their dealmaking activity amid a lack of any news. With no expected big events to shake the scene up, the euro was spotted taking tiny steps in efforts to snap three weeks of consistent losses. \n\nFor that to happen, the European currency needs to wrap up today’s session above its Monday open at $1.0785, or just about 5 pips higher than its daily session top. Markets’ recent calmness could be attributed to traders still digesting the Federal Reserve’s latest meeting on January 31. \n\nIn a nutshell, Fed Chair Jay Powell said there will be no rush from policymakers to cut interest rates. Instead, the central bank will continue monitoring incoming data and trace inflation’s trajectory to a steady drop before trimming borrowing costs. In that light, the US dollar strengthened as higher rates suggest a more expensive local currency.")]),

        StoryBundle(circleImage: "Ten", stories: [Story(imageURL: "StoryTen",
                                                        title: "USD/JPY: Dollar Chases ¥149 as Bank of Japan Signals Slow Move Away from Easy Policy",
                                                        shortDescription: "Bank of Japan Deputy Governor said officials don’t expect easy-money conditions to change too much after the end of negative rates.",
                                                        fullDescription: "Bank of Japan Deputy Governor said officials don’t expect easy-money conditions to change too much after the end of negative rates. \n\nThe USDJPY pair took off in early Thursday deals after a Bank of Japan official dampened traders’ hopes of a major shift in monetary policy. The exchange rate was on its way to cross the ¥149.00 threshold and was eyeing a 10-week high after having moved mostly sideways for the past month. \n\nBank of Japan Deputy Governor Shinichi Uchida said in a press release that Japan’s central bank is not looking to make any drastic moves in the near future. His comments signaled a gradual move away from the current negative interest rate environment as a way to maintain a stable economy.\n\nIn other words, the easy-money policy will continue to provide accommodative conditions for a considerable time span. In response, traders were quick to offload their long bets on the Japanese yen. The Asian currency was among the biggest losers of 2023 while the US dollar reigned supreme.")]),

        StoryBundle(circleImage: "Eleven", stories: [Story(imageURL: "StoryEleven",
                                                           title: "GBP/USD: Sterling Regains $1.26 in 2nd Up Day as Mosaic of Data Paints Mixed Outlook",
                                                           shortDescription: "Bank of England nods to rate cuts ahead, consumers spent less in January, and house prices hit their highest level since October 2022.",
                                                           fullDescription: "Bank of England nods to rate cuts ahead, consumers spent less in January, and house prices hit their highest level since October 2022. \n\nThe GBPUSD pair pushed higher for a second straight day on Wednesday as traders lined up their long bets on a string of economic data. The exchange rate jumped above $1.26 with a daily high of $1.2630 after floating at a weekly low of $1.2118 on Monday. The British pound is on its way to close out a second day of gains, following a steep two-day drop. \n\nThe Bank of England raised investors’ hopes of an interest-rate reduction, saying it will start trimming down borrowing costs as a “reward” for the steady drop in inflation. Consumer prices were last seen out and about at 4.0% for December, up from 3.9% in November. January’s inflation data will be released on February 14. In the meantime, interest rates stay at 5.25 to 5.50%. \n\nIn addition, retail spending slowed in January, coming in at 1.2% from a year ago. The figure was below the 1.7% growth in December, casting a shadow over the strength of consumer demand. And finally, house prices continued to pick up the pace, averaging £291,029 (roughly $370,000) between December and January. It represents a 2.5% increase from a year ago and is the highest level since October 2022.")]),

        StoryBundle(circleImage: "Twelve", stories: [Story(imageURL: "StoryTwelve",
                                                           title: "USD/JPY: Dollar Soars 1.6% to erase Two-Week Loss as January Jobs Surge to 353,000",
                                                           shortDescription: "Japanese yen took a heavy beating by returning US dollar bulls who propelled the exchange rate to ¥148.60.",
                                                           fullDescription: "Japanese yen took a heavy beating by returning US dollar bulls who propelled the exchange rate to ¥148.60. \n\nThe USDJPY pair jumped 1.6% on Friday after stunningly strong job growth tore through Wall Street’s expectations. The US labor market added a staggering 353,000 new jobs in January, far outstripping analysts’ consensus calls for 187,000 Americans tapped to join the workforce. \n\nForex traders rushed to buy up the greenback, resulting in a powerful spike across the board. The USDJPY erased a two-week loss, closing the session at ¥148.60. Early on Monday, dealmaking is slow to perk up, but the yen remains subdued as the buck reigns supreme once again. \n\nWhy the sharp leg up? The surprise hotness in the labor market is likely to present an upside risk to the Federal Reserve’s planned agenda for three rate cuts this year. More precisely, it may be too soon to trim borrowing costs at any of the next three Fed officials’ meetings through mid-June.")]),

        StoryBundle(circleImage: "Thirteen", stories: [Story(imageURL: "StoryThirteen",
                                                             title: "GBP/USD: Pound Shoots Higher by 1% as UK Skips Rate Hike, All Eyes on US Job Number",
                                                             shortDescription: "Forex traders brace for a volatility rush today when the US reports this year’s first labor-market update— the January nonfarm payrolls.",
                                                             fullDescription: "Forex traders brace for a volatility rush today when the US reports this year’s first labor-market update— the January nonfarm payrolls. \n\nThe GBPUSD pair shot sharply higher on Thursday and remained well-bid in early Friday dealmaking. The sterling jumped 1% against the dollar, crossing the $1.2750 threshold after a boost from Bank of England officials who left benchmark interest rates flat at 5.25% to 5.50%. \n\nNext up, America’s employers are in focus. It’s time for job numbers and analysts are eyeballing a cool 187,000 new hires to have been added in January. The data will be a key gauge for the Federal Reserve, who’s on the outlook for anything out of line. A value too high may sway officials to reconsider their three-rate-cuts agenda for 2024. \n\nIn that context, the GBPUSD exchange rate is looking to break out of its rather stubborn consolidation area. For the past two months, the pair has been caught in the range between $1.2600 and $1.2800. Today’s nonfarm payroll survey can provide much-needed fuel for a fresh journey into new price discovery.")]),

        StoryBundle(circleImage: "Fourteen", stories: [Story(imageURL: "StoryFourteen",
                                                             title: "EUR/USD: Dollar Gains Traction as Markets Brace for Volatility from Fed’s Rate Decision",
                                                             shortDescription: "Markets are on edge today as they fear Fed chief Powell might push back against early moves on interest rate cuts.",
                                                             fullDescription: "Markets are on edge today as they fear Fed chief Powell might push back against early moves on interest rate cuts. \n\nThe EURUSD pair declined to $1.0820 to start Wednesday dealmaking while nervous traders braced for a volatility party later today. The Federal Reserve is about to sweep all corners of the forex market with its highly anticipated first two-day meeting of 2024. A rate decision and a speech will top it off. \n\nFed Chair Jay Powell is slated to update the interest rate decision and expectations are set for a hold at the current 22-year high of 5.25% to 5.50%. More importantly, markets will be looking for clues into the central bank’s three rate cuts projected this year. But not without some anxiety flaring up. \n\nThe central banking boss, analysts warn, may use his podium time to push back against investors’ hopes for early rate cuts – a notion that has been driving untamed momentum in markets across the board. Any surprise comments may send the EURUSD spiraling, seesawing, twisting and turning.")]),

        StoryBundle(circleImage: "Fifteen", stories: [Story(imageURL: "StoryFifteen",
                                                            title: "USD/JPY: Dollar Bulls Jump Start Weekly Trade with Fresh Attack on Yen, Rate Tops ¥148",
                                                            shortDescription: "After a week of seesaw trading, the exchange rate erased a big chunk of losses to pierce the ¥148 mark.",
                                                            fullDescription: "After a week of seesaw trading, the exchange rate erased a big chunk of losses to pierce the ¥148 mark. \n\nThe USDJPY pair advanced to start weekly trading, building on the previous two days of gains. The dollar crossed ¥148.00 and threatened to break out of its short-term consolidation capped at ¥148.75 as traders anticipated a wave of events slated for the week ahead. \n\nFirst off, the Bank of Japan did not make any changes to its easy-money policies at the latest meeting. The status quo weighed on the yen as low rates are generally negative for the local currency’s valuation. And second, markets are bracing for elevated volatility out of the US. \n\nA flurry of economic news is about to sweep forex dealmaking. The US Federal Reserve gathers for its regular meeting, which wraps up on Wednesday with an interest rate decision. On Friday, the nonfarm payrolls report will show how many new jobs were created in the first month of the year. Hopes are pinned at 177,000, down from 216,000 in December.")]),

        StoryBundle(circleImage: "Sixteen", stories: [Story(imageURL: "StorySixteen",
                                                            title: "EUR/USD: Dollar Powers Up as US Economy Expands 3.3% in Q4, Euro Sinks to $1.08",
                                                            shortDescription: "Unexpected growth in the US GDP number sent traders to the greenback, lifting its valuation across all major rivals.",
                                                            fullDescription: "Unexpected growth in the US GDP number sent traders to the greenback, lifting its valuation across all major rivals. \n\nThe EURUSD pair tanked early Friday, extending its decline from a day earlier when the US revealed its economy expanded more than expected. The exchange rate tumbled roughly 1%, or 100 pips, from a Thursday high of $1.09 to a Friday session low of just around the $1.08 mark. \n\nUS gross domestic product grew by a surprise 3.3% rate for the December quarter, shooting past estimates for a modest 2% rate of expansion. The news stirred up forex dealmaking, sending the US dollar higher against all other major currencies and lifting the index DXY on track for its fourth consecutive week of green candlesticks. \n\nAcross forex corners, the USDJPY was back on the offensive, erasing some of its weekly losses to trade near the ¥148.00 handle. The GBPUSD remained under pressure early on Friday, extending its range-bound sideways trading near the $1.27 area.")]),

        StoryBundle(circleImage: "Seventeen", stories: [Story(imageURL: "StorySeventeen",
                                                              title: "GBP/USD: Sterling Extends Consolidation, Zig Zags Near $1.2750 Ahead of US PCE Data",
                                                              shortDescription: "British pound has been trading in the range between $1.2750 to $1.2700 as trades eye the next big event – PCE data.",
                                                              fullDescription: "British pound has been trading in the range between $1.2750 to $1.2700 as trades eye the next big event – PCE data. \n\nThe GBPUSD pair opened Thursday trading to the upside but kept floating in its weekslong range under the $1.2750 mark. The exchange rate added a modest 30 pips to start the day, bouncing from the $1.2700 level to notch a session high of $1.2736. What’s next for the pair? \n\nForex traders anticipate tomorrow’s economic data out of the US. The personal consumption expenditures index, or the Federal Reserve’s preferred measure of inflation, is on deck for release Friday. Analysts expect a highly upbeat figure of 3.0% for December, down from 3.2% in November. \n\nAnywhere above that number might throw the GBPUSD into whipsaw trading as speculators try to bake in rising price pressures all over again. Further, a hot-to-warm report will complicate the Fed’s timeline of three interest rate cuts for 2024 already factored in by market participants.")]),

        StoryBundle(circleImage: "Eighteen", stories: [Story(imageURL: "StoryEighteen",
                                                             title: "USD/JPY: Dollar Drops to ¥147.00 as Bank of Japan Overturns Buck’s Monster Rally",
                                                             shortDescription: "BoJ decided to keep its notorious interest rates at -0.1% and kept its yield curve control unchanged. The dollar took a tumble.",
                                                             fullDescription: "BoJ decided to keep its notorious interest rates at -0.1% and kept its yield curve control unchanged. The dollar took a tumble. \n\nThe USDJPY pair downshifted its rapid rise for a third straight day on Tuesday as early-week dealmaking picked up momentum. The exchange rate has retreated roughly 180 pips from its Friday peak of ¥148.80 as traders reacted to the Bank of Japan’s two-day meeting which wrapped up on Tuesday. \n\nJapan’s central bank said it has decided to maintain its notorious negative interest rate at -0.1%. What’s more, it stuck to its yield curve control policy with a 1%-as-a-reference yield cap to the 10-year government bond. Policymakers also trimmed core inflation forecast to 2.4%, down from an October call of 2.8%. \n\nBut it wasn’t the Bank of Japan’s commitment to support its policy which triggered a selloff reaction in the USDJPY. It was the market’s view that Japan will abandon its negative rates regime as early as April. Presently, Japan is the only country to allow negative interest rates and this approach has been suppressing the yen for years.")]),

        StoryBundle(circleImage: "Nineteen", stories: [Story(imageURL: "StoryNineteen",
                                                             title: "EUR/USD: Euro Seeks to Break Out of Sluggish Three-Day Sideways Trading Near $1.0850",
                                                             shortDescription: "The exchange rate hovered near $1.09 early Monday as FX traders girded up for increased volatility down the week.",
                                                             fullDescription: "The exchange rate hovered near $1.09 early Monday as FX traders girded up for increased volatility down the week. \n\nThe EURUSD pair advanced moderately in early Monday deals as forex market participants punched in for the week. The euro powered higher by a mere 15 pips to cross $1.09 as it struggled to break out of a three-day consolidation area around the $1.0850 threshold. \n\nThe euro got battered in the past couple of weeks as shifting sentiment positioned the dollar at the EURUSD has lost roughly 150 pips, or 1.3%, as the pair dived under the 50-day moving average, indicating short-term bearish pressure. \n\nLooking ahead, volatility is bound to pick up as economic reports stir up the trading arena. On Thursday, the European Central Bank will announce its interest rate decision. Analysts expect Europe’s central bankers to maintain the benchmark rate unchanged at 4.50%. First rate cuts are projected for June, or later than markets had expected.")]),

        StoryBundle(circleImage: "Twenty", stories: [Story(imageURL: "StoryTwenty",
                                                           title: "USD/JPY: Dollar Rally Pauses for Breath at ¥148.50 as Three-Day Streak Fizzles Out",
                                                           shortDescription: "The Japanese yen is on track to snap the dollar’s tear, but technical indicators are still supporting the bull side narrative.",
                                                           fullDescription: "The Japanese yen is on track to snap the dollar’s tear, but technical indicators are still supporting the bull side narrative. \n\nThe USDJPY downshifted its powerful rally early on Thursday as FX traders reassessed the exchange rate’s outlook. The US dollar retreated from a six-week high of ¥148.50 and is on track to snap its three-day winning streak. Economic data out of the US helped suppress the greenback. \n\nRetail sales data, an indicator of how much consumers spend, ticked up to 0.6% in December. The figure suggested that the Federal Reserve might hold back on any aggressive trims to interest rates. While higher rates generally hint at a stronger dollar, speculators decided to fold their bets on the USDJPY. \n\nWith that said, the recent upside swing – a hefty 5% since the start of the year – propelled the exchange rate above all significant moving averages. The 100-day line is now resting at ¥147.42, followed by the 50-day one at ¥146.01. The 200-day one is lurking from the depths under ¥144.00.")])
    ]

    @Published var currentRandomStories: [StoryBundle] = []

    let userDefaultsKey = "LastUpdatedDate"

    func generateRandomStories() {
        let shuffledStories = allStories.shuffled()
        currentRandomStories = Array(shuffledStories.prefix(5))
        UserDefaults.standard.set(Date(), forKey: userDefaultsKey)
        saveRandomStories()
    }

    func isDayPassed() -> Bool {
        if let lastUpdatedDate = UserDefaults.standard.object(forKey: userDefaultsKey) as? Date {
            let calendar = Calendar.current
            return calendar.isDateInYesterday(lastUpdatedDate)
        } else {
            return true
        }
    }

    func saveRandomStories() {
        if let encodedData = try? JSONEncoder().encode(currentRandomStories) {
            UserDefaults.standard.set(encodedData, forKey: "SavedRandomStories")
        }
    }

    init() {
        if isDayPassed() {
            generateRandomStories()
        } else {
            if let savedRandomStoriesData = UserDefaults.standard.data(forKey: "SavedRandomStories"),
               var savedRandomStories = try? JSONDecoder().decode([StoryBundle].self, from: savedRandomStoriesData) {
                
                for index in savedRandomStories.indices {
                    savedRandomStories[index].isSeen = UserDefaults.standard.isStorySeen(savedRandomStories[index].id)
                }

                currentRandomStories = savedRandomStories
            }
        }
    }
}
